services:
  db:
    image: mysql:8.0
    container_name: todo_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todo_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - mysql_data:/var/lib/mysql  # Здесь хранится база данных, включая миграции
    networks:
      - network-todo

  app:
    build: .
    container_name: todo_app
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor  # Отключаем vendor от хоста
    working_dir: /var/www/html
    depends_on:
      - db
    command: sh -c "php artisan serve --host=0.0.0.0 --port=8000"
    ports:
      - "8000:8000"  # Laravel будет доступен на порту 8000
    networks:
      - network-todo

networks:
  network-todo:
    driver: bridge
    
volumes:
  mysql_data:
  
